version: "3.9"

services:
  db:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 20s
    # We use a mariadb image which supports both amd64 & arm64 architecture
    #image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    #command: '--init-file /data/application/init.sql'
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init.sql:/data/application/init.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test1234
      - MYSQL_DATABASE=inner_use
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=test1234
    expose:
      - 3307:3306
      - 33060

  videoplayer:
    depends_on:
      db:
        condition: service_healthy
    image: videoplayer:latest
    volumes:
      - videoplayer_data:/var/www/html
      - D:\Torrent:/var/video/root
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://db:3306/inner_use?&useSSL=false&useJDBCComplaintTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true",
            "spring.datasource.username" : "developer",
            "spring.datasource.password" : "test1234",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
volumes:
  db_data: {}
  videoplayer_data: {}
